{{- define "keystone.templates.lifecycle.backup" -}}
{{- $envAll := . }}
# The workflow checks that all the jobs and services required for
# keystone-api to start are here.

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: keystone-backup
  namespace: {{ $envAll.Release.Namespace }}
spec:
  entrypoint: keystone-backup
  serviceAccountName: wf-keystone-sa
  volumes:
  {{- include "keystone.templates.steps._db_dump.volumes" . | nindent 2 }}
  templates:
  - name: wf-keystone-backup
    steps:
    - - name: task-keystone-db-dump
        template: task-keystone-db-dump

  - name: task-keystone-db-dump
    activeDeadlineSeconds: {{ .Values.dependencies.timeout.tasks.db_dump }}
    retryStrategy:
      limit: {{ .Values.dependencies.retries.db_dump }}
    container:
    {{- include "keystone.templates.steps._db_dump.container" . | nindent 6 }}
{{- end }}
