{{- if eq .Values.oslc.stage "install" }}
{{- $envAll := . }}
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ printf "%s-%s-%s" $envAll.Release.Name "install" "stage" | quote }}
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: [{{ printf "%s %s-%s-%s" "Executing install:" $envAll.Release.Name "install" "stage" | quote }}]
{{ end }}

{{- if eq .Values.oslc.stage "futureinstall" }}
{{- $envAll := . }}
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: mariadb
spec:
  chart_name: mariadb
  release: mariadb
  namespace: {{ $envAll.Release.Namespace }}
  wait:
    timeout: 3600
    labels:
      release_group: armada-mariadb
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: local
    location: /opt/armada/helm-charts/mariadb
    subpath: .
    reference: master
  dependencies:
    - helm-toolkit
  target_state: uninitialized
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: memcached
spec:
  chart_name: memcached
  release: memcached
  namespace: {{ $envAll.Release.Namespace }}
  wait:
    timeout: 100
    labels:
      release_group: armada-memcached
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: local
    location: /opt/armada/helm-charts/memcached
    subpath: .
    reference: master
  dependencies:
    - helm-toolkit
  target_state: uninitialized
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: rabbitmq
spec:
  chart_name: rabbitmq
  test:
    enabled: true
  release: rabbitmq
  namespace: {{ $envAll.Release.Namespace }}
  wait:
    timeout: 100
    labels:
      release_group: armada-rabbitmq
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: local
    location: /opt/armada/helm-charts/rabbitmq
    subpath: .
    reference: master
  dependencies:
    - helm-toolkit
  target_state: uninitialized
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: keystone
spec:
  chart_name: keystone
  test:
    enabled: true
  release: keystone
  namespace: {{ $envAll.Release.Namespace }}
  wait:
    timeout: 100
    labels:
      release_group: armada-keystone
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - name: keystone-bootstrap
          type: job
          labels:
            application: keystone
            component: bootstrap
  values:
    replicas: 3
#  values:
#    bootstrap:
#      script: |
#        openstack domain create 'ucp'
#        openstack project create --domain 'ucp' 'service'
#        openstack user create --domain ucp --project service --project-domain 'ucp' --password armada armada
#        openstack role add --project-domain ucp --user-domain ucp --user armada --project service admin
  source:
    type: local
    location: /opt/armada/helm-charts/keystone
    subpath: .
    reference: master
  dependencies:
    - helm-toolkit
  target_state: uninitialized
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: armada-manifest
spec:
  entrypoint: armada-manifest
  serviceAccountName: armada-argo-sa
  templates:
  - name: armada-manifest
    dag:
      tasks:
      - name: keystone-infra-services
        template: keystone-infra-services-template
      - name: openstack-keystone
        template: openstack-keystone-template

  - name: openstack-keystone-template
    steps:
    - - name: enable-keystone
        template: enable-keystone-template
    - - name: keystone-ready
        template: keystone-ready-template

  - name: keystone-infra-services-template
    steps:
    - - name: enable-mariadb
        template: enable-mariadb-template
    - - name: mariadb-ready
        template: mariadb-ready-template
    - - name: enable-memcached
        template: enable-memcached-template
    - - name: memcached-ready
        template: memcached-ready-template
    - - name: enable-rabbitmq
        template: enable-rabbitmq-template
    - - name: rabbitmq-ready
        template: rabbitmq-ready-template

  - name: enable-mariadb-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: mariadb
        spec:
          target_state: deployed

  - name: mariadb-ready-template
    resource:
      action: get
      successCondition: status.actual_state == deployed
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: mariadb

  - name: enable-memcached-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: memcached
        spec:
          target_state: deployed

  - name: memcached-ready-template
    resource:
      action: get
      successCondition: status.actual_state == deployed
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: memcached

  - name: enable-rabbitmq-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: rabbitmq
        spec:
          target_state: deployed

  - name: rabbitmq-ready-template
    resource:
      action: get
      successCondition: status.actual_state == deployed
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: rabbitmq

  - name: enable-keystone-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: keystone
        spec:
          target_state: deployed

  - name: keystone-ready-template
    resource:
      action: get
      successCondition: status.actual_state == deployed
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: keystone
{{ end }}
