apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: openstackdeployments.openstacklcm.airshipit.org
spec:
  additionalPrinterColumns:
  - JSONPath: .status.succeeded
    description: Succeeded
    name: Succeeded
    type: boolean
  group: openstacklcm.airshipit.org
  names:
    kind: OpenstackDeployment
    plural: openstackdeployments
    shortNames:
    - odpl
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            openstackRevision:
              description: OpenstackRevision is the revision of openstack's KV store
                where the backup is performed on.
              format: int64
              type: integer
            openstackVersion:
              description: OpenstackVersion is the version of the backup openstack
                server.
              type: string
          type: object
        status:
          properties:
            openstackRevision:
              description: OpenstackRevision is the revision of openstack's KV store
                where the backup is performed on.
              format: int64
              type: integer
            openstackVersion:
              description: OpenstackVersion is the version of the backup openstack
                server.
              type: string
            reason:
              description: Reason indicates the reason for any backup related failures.
              type: string
            succeeded:
              description: Succeeded indicates if the backup has Succeeded.
              type: boolean
          required:
          - succeeded
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
