---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: keystone
spec:
  chart_name: keystone
  release: keystone
  namespace: default
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: local
    location: /opt/armada/helm-charts/keystone
    subpath: .
    reference: 87aad18f7d8c6a1a08f3adc8866efd33bee6aa52
  dependencies: []
  target_state: initialized
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChartGroup
metadata:
  name: keystone
spec:
  description: Deploys MariaDB
  sequenced: False
  chart_group:
    - keystone
  target_state: initialized
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaManifest
metadata:
  name: keystone
spec:
  release_prefix: armada
  chart_groups:
    - keystone
  target_state: initialized
