apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: helmrequests.armada.airshipit.org
spec:
  additionalPrinterColumns:
  - JSONPath: .status.succeeded
    description: success
    name: succeeded
    priority: 1
    type: boolean
  group: armada.airshipit.org
  names:
    kind: HelmRequest
    plural: helmrequests
    shortNames:
    - hreq
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            apply:
              description: Install the HelmManifest specified int the request
              properties:
                chart:
                  description: Chart is the protobuf representation of a chart.
                  type: object
                name:
                  description: Name is the candidate release name. This must be unique
                    to the namespace, otherwise the server will return an error. If
                    it is not supplied, the server will autogenerate one.
                  type: string
                namespace:
                  description: Namepace is the kubernetes namespace of the release.
                  type: string
                timeout:
                  description: timeout specifies the max amount of time any kubernetes
                    client command can run.
                  format: int64
                  type: integer
                values:
                  description: Values is a string containing (unparsed) YAML values.
                  type: object
                wait:
                  description: wait, if true, will wait until all Pods, PVCs, and
                    Services are in a ready state before marking the release as successful.
                    It will wait for as long as timeout
                  type: boolean
              type: object
            delete:
              description: Delete the HelmRelease specified in the request
              properties:
                force:
                  description: Force resource update through delete/recreate if needed.
                  type: boolean
                name:
                  description: The name of the release
                  type: string
                recreate:
                  description: Performs pods restart for resources if applicable
                  type: boolean
                timeout:
                  description: timeout specifies the max amount of time any kubernetes
                    client command can run.
                  format: int64
                  type: integer
                version:
                  description: Version is the version of the release to deploy.
                  format: int64
                  type: integer
                wait:
                  description: wait, if true, will wait until all Pods, PVCs, and
                    Services are in a ready state before marking the release as successful.
                    It will wait for as long as timeout
                  type: boolean
              type: object
            rollback:
              description: Rollback the HelmRelease specified in the request
              properties:
                force:
                  description: Force resource update through delete/recreate if needed.
                  type: boolean
                name:
                  description: The name of the release
                  type: string
                recreate:
                  description: Performs pods restart for resources if applicable
                  type: boolean
                timeout:
                  description: timeout specifies the max amount of time any kubernetes
                    client command can run.
                  format: int64
                  type: integer
                version:
                  description: Version is the version of the release to deploy.
                  format: int64
                  type: integer
                wait:
                  description: wait, if true, will wait until all Pods, PVCs, and
                    Services are in a ready state before marking the release as successful.
                    It will wait for as long as timeout
                  type: boolean
              type: object
            upgrade:
              description: Upgrade the HelmRelease specified in the request
              properties:
                chart:
                  description: Chart is the protobuf representation of a chart.
                  type: object
                force:
                  description: Force resource update through delete/recreate if needed.
                  type: boolean
                name:
                  description: The name of the release
                  type: string
                recreate:
                  description: Performs pods restart for resources if applicable
                  type: boolean
                timeout:
                  description: timeout specifies the max amount of time any kubernetes
                    client command can run.
                  format: int64
                  type: integer
                values:
                  description: Values is a string containing (unparsed) YAML values.
                  type: object
                wait:
                  description: wait, if true, will wait until all Pods, PVCs, and
                    Services are in a ready state before marking the release as successful.
                    It will wait for as long as timeout
                  type: boolean
              type: object
          type: object
        status:
          properties:
            Reason:
              description: Reason indicates the reason for any related failures.
              type: string
            succeeded:
              description: Succeeded indicates if the release is in the expected state
              type: boolean
          required:
          - succeeded
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
