{{- if or (eq .Values.oslc.stage "install") (eq .Values.lifecycle "install") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: wf-{{ .Values.serviceName }}-role
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
      - argoproj.io
    resources:
      - secrets
      - services
      - endpoints
      - jobs
      - pods
      - workflows
      - workflows/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wf-{{ .Values.serviceName }}-rolebinding
subjects:
- kind: ServiceAccount
  name: wf-{{ .Values.serviceName }}-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wf-{{ .Values.serviceName }}-role
---
{{- $serviceAccountName := "wf-{{ .Values.serviceName }}-sa" }}
{{ tuple . "wf-{{ .Values.serviceName }}" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
{{- end}}
