apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: DeletePhase
metadata:
  name: delete-phase
spec:
  openstackServiceName: testservice
  targetOpenstackServiceVersion: moc.version.to.delete.to
  targetState: deployed
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/testservice
    subpath: .
