apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: InstallPhase
metadata:
  name: install-phase
spec:
  openstackServiceName: testservice
  targetOpenstackServiceVersion: moc.version.to.install.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/testservice
    subpath: .
