apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: PlanningPhase
metadata:
  name: planning-phase
spec:
  openstackServiceName: testservice
  targetOpenstackServiceVersion: moc.version.to.planning.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/testservice
    subpath: .
