apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: RollbackPhase
metadata:
  name: rollback-phase
spec:
  openstackServiceName: testservice
  targetOpenstackServiceVersion: moc.version.to.rollback.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/testservice
    subpath: .

  backupStorageType: offsite
  # ceph:
  #   cephSecret: thesecret
  #   path: example
  offsite:
    endpoint: sftp://foo.bar
    forcePathStyle: true
    offsiteSecret: thesecret
    path: xxx
  openstackEndpoints:
  - https://tar.com
