apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TestPhase
metadata:
  name: test-phase
spec:
  openstackServiceName: testservice
  targetOpenstackServiceVersion: moc.version.to.test.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/testservice
    subpath: .
