apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TrafficDrainPhase
metadata:
  name: trafficdrain-phase
spec:
  openstackServiceName: testservice
  targetOpenstackServiceVersion: moc.version.to.trafficdrain.to
  targetState: deployed
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/testservice
    subpath: .
