---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: rabbitmq-manifest
spec:
  entrypoint: rabbitmq-manifest
  serviceAccountName: armada-argo-sa
  templates:
  - name: rabbitmq-manifest
    dag:
      tasks:
      - name: rabbitmq-chartgroup
        template: rabbitmq-chartgroup-template

  - name: rabbitmq-chartgroup-template
    steps:
    - - name: enable-rabbitmq
        template: enable-rabbitmq-template
    - - name: rabbitmq-ready
        template: rabbitmq-ready-template

  - name: enable-rabbitmq-template
    activeDeadlineSeconds: 60
    retryStrategy:
      limit: 1
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: rabbitmq
        spec:
          target_state: deployed

  - name: rabbitmq-ready-template
    activeDeadlineSeconds: 120
    retryStrategy:
      limit: 2
    resource:
      action: get
      successCondition: status.actual_state == deployed
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: rabbitmq
