apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: PlanningPhase
metadata:
  name: planning
spec:
  openstackServiceVersion: moc.version.to.planning.to
  target_state: deployed
  source:
    type: local
    location: /opt/openstacklcm-operator/oslc-phases/testservice/wf-planning.yaml
    subpath: .
