apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TestPhase
metadata:
  name: test-phase
spec:
  openstackServiceName: testservice
  targetOpenstackServiceVersion: moc.version.to.test.to
  targetState: deployed
  source:
    type: local
    location: /opt/openstacklcm-operator/oslc-phases/testservice/wf-test.yaml
    subpath: .
