apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: OperationalPhase
metadata:
  name: operational-phase
spec:
  openstackServiceName: testservice
  targetOpenstackServiceVersion: moc.version.to.operational.to
  targetState: deployed
  source:
    type: local
    location: /opt/openstacklcm-operator/oslc-phases/testservice/wf-operational.yaml
    subpath: .
