apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: OperationalPhase
metadata:
  name: operational
spec:
  openstackServiceVersion: moc.version.to.operational.to
  target_state: deployed
  source:
    type: local
    location: /opt/openstacklcm-operator/oslc-phases/testservice/wf-operational.yaml
    subpath: .
