---
{{- define "keystone.templates.steps._db_init.ignore" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keystone-db-init
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: release-name-keystone-db-init
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-default-keystone-db-init
subjects:
  - kind: ServiceAccount
    name: keystone-db-init
    namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: release-name-default-keystone-db-init
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "keystone-db-init"
spec:
  template:
    metadata:
      labels:
        release_group: release-name
        application: keystone
        component: db-init
    spec:
      serviceAccountName: keystone-db-init
      restartPolicy: OnFailure
      nodeSelector:
        openstack-control-plane: enabled

      initContainers:


        - name: init
          image: "quay.io/stackanetes/kubernetes-entrypoint:v0.3.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:mariadb"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: COMMAND
              value: "echo done"
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []

      containers:
        - name: "keystone-db-init-0"
{{- end }}

{{- define "keystone.templates.steps._db_init.container" -}}
name: "keystone-db-init-0"
image: docker.io/openstackhelm/heat:ocata
imagePullPolicy: IfNotPresent

env:
  - name: ROOT_DB_CONNECTION
    valueFrom:
      secretKeyRef:
        name: "keystone-db-admin"
        key: DB_CONNECTION
  - name: OPENSTACK_CONFIG_FILE
    value: "/etc/keystone/keystone.conf"
  - name: OPENSTACK_CONFIG_DB_SECTION
    value: "database"
  - name: OPENSTACK_CONFIG_DB_KEY
    value: "connection"
command:
  - /tmp/db-init.py
volumeMounts:
  - name: db-init-sh
    mountPath: /tmp/db-init.py
    subPath: db-init.py
    readOnly: true
  - name: etc-service
    mountPath: "/etc/keystone"
  - name: db-init-conf
    mountPath: "/etc/keystone/keystone.conf"
    subPath: "keystone.conf"
    readOnly: true
  - name: db-init-conf
    mountPath: "/etc/keystone/logging.conf"
    subPath: "logging.conf"
    readOnly: true
{{- end }}

{{- define "keystone.templates.steps._db_init.volumes" -}}
- name: db-init-sh
  configMap:
    name: "keystone-bin"
    defaultMode: 0555
- name: etc-service
  emptyDir: {}
- name: db-init-conf
  secret:
    secretName: "keystone-etc"
    defaultMode: 0444
{{- end }}
