---
{{- define "keystone.templates.steps._db_sync.ignore" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keystone-db-sync
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: release-name-keystone-db-sync
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-default-keystone-db-sync
subjects:
  - kind: ServiceAccount
    name: keystone-db-sync
    namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: release-name-default-keystone-db-sync
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "keystone-db-sync"
spec:
  template:
    metadata:
      labels:
        release_group: release-name
        application: keystone
        component: db-sync
    spec:
      serviceAccountName: keystone-db-sync
      restartPolicy: OnFailure
      nodeSelector:
        openstack-control-plane: enabled

      initContainers:


        - name: init
          image: "quay.io/stackanetes/kubernetes-entrypoint:v0.3.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:mariadb"
            - name: DEPENDENCY_JOBS
              value: "keystone-db-init,keystone-credential-setup,keystone-fernet-setup,keystone-rabbit-init"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: COMMAND
              value: "echo done"
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []

      containers:
        - name: "keystone-db-sync"
{{- end }}

{{- define "keystone.templates.steps._db_sync.container" -}}
name: "keystone-db-sync"
image: "docker.io/openstackhelm/keystone:ocata"
imagePullPolicy: "IfNotPresent"

env:
  - name: OS_BOOTSTRAP_ADMIN_URL
    value: http://keystone.openstack.svc.cluster.local:80/v3
  - name: OS_BOOTSTRAP_INTERNAL_URL
    value: http://keystone-api.openstack.svc.cluster.local:5000/v3
  - name: OS_BOOTSTRAP_PUBLIC_URL
    value: http://keystone.openstack.svc.cluster.local:80/v3
  - name: OPENSTACK_CONFIG_FILE
    value: /etc/keystone/keystone.conf
  - name: OPENSTACK_CONFIG_DB_SECTION
    value: database
  - name: OPENSTACK_CONFIG_DB_KEY
    value: connection
  - name: OS_IDENTITY_API_VERSION
    value: "3"
  - name: OS_AUTH_URL
    valueFrom:
      secretKeyRef:
        key: OS_AUTH_URL
        name: keystone-keystone-admin
  - name: OS_REGION_NAME
    valueFrom:
      secretKeyRef:
        key: OS_REGION_NAME
        name: keystone-keystone-admin
  - name: OS_INTERFACE
    valueFrom:
      secretKeyRef:
        key: OS_INTERFACE
        name: keystone-keystone-admin
  - name: OS_PROJECT_DOMAIN_NAME
    valueFrom:
      secretKeyRef:
        key: OS_PROJECT_DOMAIN_NAME
        name: keystone-keystone-admin
  - name: OS_PROJECT_NAME
    valueFrom:
      secretKeyRef:
        key: OS_PROJECT_NAME
        name: keystone-keystone-admin
  - name: OS_USER_DOMAIN_NAME
    valueFrom:
      secretKeyRef:
        key: OS_USER_DOMAIN_NAME
        name: keystone-keystone-admin
  - name: OS_USERNAME
    valueFrom:
      secretKeyRef:
        key: OS_USERNAME
        name: keystone-keystone-admin
  - name: OS_PASSWORD
    valueFrom:
      secretKeyRef:
        key: OS_PASSWORD
        name: keystone-keystone-admin

command:
  - /tmp/db-sync.sh
volumeMounts:
  - name: db-sync-sh
    mountPath: /tmp/db-sync.sh
    subPath: db-sync.sh
    readOnly: true
  - name: etc-service
    mountPath: "/etc/keystone"
  - name: db-sync-conf
    mountPath: "/etc/keystone/keystone.conf"
    subPath: "keystone.conf"
    readOnly: true
  - name: db-sync-conf
    mountPath: "/etc/keystone/logging.conf"
    subPath: "logging.conf"
    readOnly: true
  - mountPath: /tmp/endpoint-update.py
    name: db-sync-sh
    readOnly: true
    subPath: endpoint-update.py
  - mountPath: /etc/keystone/fernet-keys/
    name: keystone-fernet-keys
    readOnly: true
{{- end }}

{{- define "keystone.templates.steps._db_sync.volumes" -}}
- name: db-sync-sh
  configMap:
    name: "keystone-bin"
    defaultMode: 0555
- name: etc-service
  emptyDir: {}
- name: db-sync-conf
  secret:
    secretName: "keystone-etc"
    defaultMode: 0444
- name: keystone-fernet-keys
  secret:
    secretName: keystone-fernet-keys
{{- end }}

