---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: armada-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - '*'
- apiGroups:
  - armada.airshipit.org
  resources:
  - helmreleases
  - helmreleases/status
  - armadamanifests
  - armadamanifests/status
  - armadacharts
  - armadacharts/status
  - armadachartgroups
  - armadachartgroups/status
  - helmrequests
  - helmrequests/status
  - armadarequests
  - armadarequests/status
  verbs:
  - '*'
- apiGroups:
  - helm3crd.airshipit.org
  resources:
  - releases
  - releases/status
  - manifests
  - manifests/status
  - lifecycles
  - lifecycles/status
  - lifecycleevents
  - lifecycleevents/status
  - values
  - values/status
  - releaseaudits
  - releaseaudits/status
  verbs:
  - '*'
