---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: memcached
spec:
  chart_name: memcached
  release: memcached
  namespace: openstack
  wait:
    timeout: 100
    labels:
      release_group: armada-memcached
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: local
    location: /opt/armada/helm-charts/memcached
    subpath: .
    reference: master
  dependencies:
    - helm-toolkit
  admin_state: disabled
  target_state: deployed
