---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: memcached-manifest
spec:
  entrypoint: memcached-manifest
  serviceAccountName: armada-argo-sa
  templates:
  - name: memcached-manifest
    dag:
      tasks:
      - name: memcached-chartgroup
        template: memcached-chartgroup-template

  - name: memcached-chartgroup-template
    steps:
    - - name: enable-memcached
        template: enable-memcached-template
    - - name: memcached-ready
        template: memcached-ready-template

  - name: enable-memcached-template
    activeDeadlineSeconds: 60
    retryStrategy:
      limit: 1
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: memcached
        spec:
          target_state: deployed

  - name: memcached-ready-template
    activeDeadlineSeconds: 120
    retryStrategy:
      limit: 2
    resource:
      action: get
      successCondition: status.actual_state == deployed
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: memcached
