---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: memcached
spec:
  chart_name: memcached
  release: memcached
  namespace: default
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: local
    location: /opt/armada/helm-charts/memcached
    subpath: .
    reference: 87aad18f7d8c6a1a08f3adc8866efd33bee6aa52
  dependencies: []
  target_state: initialized
