---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: armada-manifest
spec:
  entrypoint: armada-manifest
  serviceAccountName: armada-argo-sa
  templates:
  - name: armada-manifest
    dag:
      tasks:
      - name: keystone-infra-services
        template: keystone-infra-services-template
      - name: openstack-keystone
        template: openstack-keystone-template

  - name: openstack-keystone-template
    steps:
    - - name: enable-keystone
        template: enable-keystone-template
    - - name: keystone-ready
        template: keystone-ready-template

  - name: keystone-infra-services-template
    steps:
    - - name: enable-mariadb
        template: enable-mariadb-template
    - - name: mariadb-ready
        template: mariadb-ready-template
    - - name: enable-memcached
        template: enable-memcached-template
    - - name: memcached-ready
        template: memcached-ready-template

  - name: enable-mariadb-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: mariadb
        spec:
          admin_state: enabled

  - name: mariadb-ready-template
    resource:
      action: get
      successCondition: status.satisfied == true
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: mariadb

  - name: enable-memcached-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: memcached
        spec:
          admin_state: enabled

  - name: memcached-ready-template
    resource:
      action: get
      successCondition: status.satisfied == true
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: memcached

  - name: enable-rabbitmq-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: rabbitmq
        spec:
          admin_state: enabled

  - name: rabbitmq-ready-template
    resource:
      action: get
      successCondition: status.satisfied == true
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: rabbitmq

  - name: enable-keystone-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: keystone
        spec:
          admin_state: enabled

  - name: keystone-ready-template
    resource:
      action: get
      successCondition: status.satisfied == true
      manifest: |
        apiVersion: armada.airshipit.org/v1alpha1
        kind: ArmadaChart
        metadata:
          name: keystone
