{{- if eq .Values.oslc.stage "rollback" }}
{{- $envAll := . }}

---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ $envAll.Release.Name }}
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: [{{ printf "%s %s-%s" "Executing rollback:" $envAll.Release.Name "rollback" | quote }}]
{{ end }}
