{{- if eq .Values.oslc.stage "operational" }}
{{- $envAll := . }}

---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ printf "%s-%s-%s" $envAll.Release.Name "operational" "stage" | quote }}
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: [{{ printf "%s %s-%s-%s" "Executing operational:" $envAll.Release.Name "operational" "stage" | quote }}]
{{ end }}
