apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: helmreleases.armada.airshipit.org
spec:
  additionalPrinterColumns:
  - JSONPath: .status.succeeded
    description: success
    name: succeeded
    priority: 1
    type: boolean
  group: armada.airshipit.org
  names:
    kind: HelmRelease
    plural: helmreleases
    shortNames:
    - hrel
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            chartDir:
              description: Path the chart in the container. Will be converted to a
                container later
              type: string
            releaseDesc:
              description: ReleaseDesc is the chart that was released.
              properties:
                chart:
                  description: Chart is the chart that was released.
                  type: object
                config:
                  description: Config is the set of extra Values added to the chart.
                    These values override the default values inside of the chart.
                  type: object
                hooks:
                  description: Hooks are all of the hooks declared for this release.
                  items:
                    properties:
                      events:
                        description: Events are the events that this hook fires on.
                        items:
                          type: string
                        type: array
                      kind:
                        description: Kind is the Kubernetes kind.
                        type: string
                      manifest:
                        description: Manifest is the manifest contents.
                        type: string
                      name:
                        type: string
                      path:
                        description: Path is the chart-relative path to the template.
                        type: string
                      weight:
                        description: Weight indicates the sort order for execution
                          among similar Hook type
                        format: int64
                        type: integer
                    type: object
                  type: array
                info:
                  description: Info provides information about a release
                  properties:
                    Description:
                      description: Description is human-friendly "log entry" about
                        this release.
                      type: string
                    deleted:
                      description: Deleted tracks when this object was deleted.
                      format: date-time
                      type: string
                    notes:
                      description: Contains the rendered templates/NOTES.txt if available
                      type: string
                    resources:
                      description: Cluster resources as kubectl would print them.
                      type: string
                    status:
                      description: Status is the current state of the release
                      type: string
                  type: object
                manifest:
                  description: Manifest is the string representation of the rendered
                    template.
                  type: string
                name:
                  description: Name is the name of the release
                  type: string
                namespace:
                  description: Namespace is the kubernetes namespace of the release.
                  type: string
                version:
                  description: Version is an int which represents the version of the
                    release.
                  format: int64
                  type: integer
              type: object
            releaseName:
              description: Helm Chart releate information
              type: string
            targetState:
              description: Target state of the Helm Custom Resources
              type: string
            watchHelmDependentResources:
              description: Set to true to add Watch to Kubernetes Resources created
                by the chart
              type: boolean
          required:
          - watchHelmDependentResources
          - targetState
          type: object
        status:
          properties:
            conditions:
              description: 'List of conditions and states related to the resource.
                JEB: Feature kind of overlap with event recorder'
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  resourceName:
                    type: string
                  resourceVersion:
                    format: int32
                    type: integer
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            reason:
              description: Reason indicates the reason for any related failures.
              type: string
            succeeded:
              description: Succeeded indicates if the release is in the expected state
              type: boolean
          required:
          - succeeded
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
