---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: armada-operator
rules:
- apiGroups:
  - armada.airshipit.org
  resources:
  - helmreleases
  - helmreleases/status
  verbs:
  - '*'
