apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openstacklcms.openstackhelm.openstack.org
spec:
  group: openstackhelm.openstack.org
  names:
    kind: Openstacklcm
    listKind: OpenstacklcmList
    plural: openstacklcms
    singular: openstacklcm
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
