apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openstackdeployments.openstackhelm.openstack.org
spec:
  group: openstackhelm.openstack.org
  names:
    kind: OpenstackDeployment
    listKind: OpenstackDeploymentList
    plural: openstackdeployments
    singular: openstackdeployment
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
