---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChartGroup
metadata:
  name: mariadb-group
spec:
  description: Deploys mariadb Chart
  sequenced: True
  chart_group:
    - mariadb
  target_state: uninitialized
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaManifest
metadata:
  name: mariadb-manifest
spec:
  release_prefix: armada
  chart_groups:
    - mariadb-group
  target_state: deployed
