---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: mariadb
spec:
  chart_name: mariadb
  release: mariadb
  namespace: openstack
  wait:
    timeout: 3600
    labels:
      release_group: armada-mariadb
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: local
    location: /opt/armada/helm-charts/mariadb
    subpath: .
    reference: master
  dependencies:
    - helm-toolkit
  admin_state: disabled
  target_state: deployed
