# Create a service account 
apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: wf-chartgroup-sa
--- 
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata: 
  labels: 
    rbac.authorization.k8s.io/aggregate-to-edit: "true" 
  name: wf-chartgroup-role
rules: 
  - apiGroups: 
      - argoproj.io 
    resources: 
      - workflows 
      - workflows/finalizers 
    verbs: 
      - create 
      - delete 
      - deletecollection 
      - get 
      - list 
      - patch 
      - update 
      - watch 
  - apiGroups: 
      - armada.airshipit.org
    resources: 
      - armadacharts 
      - armadacharts/finalizers 
    verbs: 
      - create 
      - delete 
      - deletecollection 
      - get 
      - list 
      - patch 
      - update 
      - watch 
--- 
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding 
metadata: 
  name: wf-chartgroup-rolebinding
subjects: 
- kind: ServiceAccount 
  name: wf-chartgroup-sa
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: Role 
  name: wf-chartgroup-role
