apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: RollbackPhase
metadata:
  name: rollback
spec:
  openstackVersion: moc.version.to.rollback.to
  openstackRevision: 3
  backupStorageType: offsite
  # ceph:
  #   cephSecret: thesecret
  #   path: example
  offsite:
    endpoint: sftp://foo.bar
    forcePathStyle: true
    offsiteSecret: thesecret
    path: xxx
  openstackEndpoints:
  - https://local.com
  target_state: deployed
