---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChartGroup
metadata:
  name: keystone-infra-services
spec:
  description: "Keystone Infra Services"
  sequenced: True
  chart_group:
    - mariadb
    - memcached
    - rabbitmq
  admin_state: disabled
  target_state: deployed
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChartGroup
metadata:
  name: openstack-keystone
spec:
  description: "Deploying OpenStack Keystone"
  sequenced: True
  chart_group:
    - keystone
  admin_state: disabled
  target_state: deployed
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaManifest
metadata:
  name: armada-manifest
spec:
  release_prefix: armada
  chart_groups:
    - keystone-infra-services
    - openstack-keystone
  admin_state: enabled
  target_state: deployed
