{{- if eq .Values.oslc.flow_kind "install" }}
{{- $envAll := . }}

---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: InstallPhase
metadata:
  name: {{ .Values.serviceName }}-install-phase
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.install.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TestPhase
metadata:
  name: {{ .Values.serviceName }}-test-phase
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.test.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TrafficRolloutPhase
metadata:
  name: {{ .Values.serviceName }}-trafficrollout-phase
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.trafficrollout.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ .Values.serviceName }}-install
spec:
  entrypoint: {{ .Values.serviceName }}-install
  serviceAccountName: openstacklcm-argo-sa
  templates:
  - name: {{ .Values.serviceName }}-install
    steps:
    - - name: {{ .Values.serviceName }}-enable-phase-install
        template: enable-phase-install-template
    - - name: {{ .Values.serviceName }}-phase-install-ready
        template: phase-install-ready-template
    - - name: {{ .Values.serviceName }}-enable-phase-test
        template: enable-phase-test-template
    - - name: {{ .Values.serviceName }}-phase-test-ready
        template: phase-test-ready-template
    - - name: {{ .Values.serviceName }}-enable-phase-trafficrollout
        template: enable-phase-trafficrollout-template
    - - name: {{ .Values.serviceName }}-phase-trafficrollout-ready
        template: phase-trafficrollout-ready-template

  - name: enable-phase-install-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: InstallPhase
        metadata:
          name: {{ .Values.serviceName }}-install-phase
        spec:
          targetState: deployed

  - name: phase-install-ready-template
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: InstallPhase
        metadata:
          name: {{ .Values.serviceName }}-install-phase

  - name: enable-phase-test-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TestPhase
        metadata:
          name: {{ .Values.serviceName }}-test-phase
        spec:
          targetState: deployed

  - name: phase-test-ready-template
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TestPhase
        metadata:
          name: {{ .Values.serviceName }}-test-phase

  - name: enable-phase-trafficrollout-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout-phase
        spec:
          targetState: deployed

  - name: phase-trafficrollout-ready-template
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout-phase
{{ end }}
