{{- if eq .Values.oslc.flow_kind "rollback" }}
{{- $envAll := . }}

---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: RollbackPhase
metadata:
  name: {{ .Values.serviceName }}-rollback-phase
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.rollback.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}

  backupStorageType: offsite
  # ceph:
  #   cephSecret: thesecret
  #   path: example
  offsite:
    endpoint: sftp://foo.bar
    forcePathStyle: true
    offsiteSecret: thesecret
    path: xxx
  openstackEndpoints:
  - https://tar.com
---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TrafficDrainPhase
metadata:
  name: {{ .Values.serviceName }}-trafficdrain-phase
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.trafficdrain.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TrafficRolloutPhase
metadata:
  name: {{ .Values.serviceName }}-trafficrollout-phase
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.trafficrollout.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ .Values.serviceName }}-rollback
spec:
  entrypoint: {{ .Values.serviceName }}-rollback
  serviceAccountName: openstacklcm-argo-sa
  templates:
  - name: {{ .Values.serviceName }}-rollback
    steps:
    - - name: {{ .Values.serviceName }}-enable-phase-trafficdrain
        template: enable-phase-trafficdrain-template
    - - name: {{ .Values.serviceName }}-phase-trafficdrain-ready
        template: phase-trafficdrain-ready-template


    - - name: {{ .Values.serviceName }}-enable-phase-rollback
        template: enable-phase-rollback-template
    - - name: {{ .Values.serviceName }}-phase-rollback-ready
        template: phase-rollback-ready-template

    - - name: {{ .Values.serviceName }}-enable-phase-trafficrollout
        template: enable-phase-trafficrollout-template
    - - name: {{ .Values.serviceName }}-phase-trafficrollout-ready
        template: phase-trafficrollout-ready-template

  - name: enable-phase-rollback-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: RollbackPhase
        metadata:
          name: {{ .Values.serviceName }}-rollback-phase
        spec:
          targetState: deployed

  - name: phase-rollback-ready-template
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: RollbackPhase
        metadata:
          name: {{ .Values.serviceName }}-rollback-phase

  - name: enable-phase-trafficdrain-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficDrainPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficdrain-phase
        spec:
          targetState: deployed

  - name: phase-trafficdrain-ready-template
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficDrainPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficdrain-phase

  - name: enable-phase-trafficrollout-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout-phase
        spec:
          targetState: deployed

  - name: phase-trafficrollout-ready-template
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout-phase

{{ end }}
