{{- if eq .Values.oslc.flow_kind "uninstall" }}
{{- $envAll := . }}

---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: DeletePhase
metadata:
  name: {{ .Values.serviceName }}-delete-phase
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.delete.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TrafficDrainPhase
metadata:
  name: {{ .Values.serviceName }}-trafficdrain-phase
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.trafficdrain.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ .Values.serviceName }}-uninstall
spec:
  entrypoint: {{ .Values.serviceName }}-uninstall
  serviceAccountName: openstacklcm-argo-sa
  templates:
  - name: {{ .Values.serviceName }}-uninstall
    steps:
    - - name: {{ .Values.serviceName }}-enable-phase-trafficdrain
        template: enable-phase-trafficdrain-template
    - - name: {{ .Values.serviceName }}-phase-trafficdrain-ready
        template: phase-trafficdrain-ready-template
    - - name: {{ .Values.serviceName }}-enable-phase-delete
        template: enable-phase-delete-template
    - - name: {{ .Values.serviceName }}-phase-delete-ready
        template: phase-delete-ready-template

  - name: enable-phase-delete-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: DeletePhase
        metadata:
          name: {{ .Values.serviceName }}-delete-phase
        spec:
          targetState: deployed

  - name: phase-delete-ready-template
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: DeletePhase
        metadata:
          name: {{ .Values.serviceName }}-delete-phase

  - name: enable-phase-trafficdrain-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficDrainPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficdrain-phase
        spec:
          targetState: deployed

  - name: phase-trafficdrain-ready-template
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficDrainPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficdrain-phase

  - name: enable-phase-trafficrollout-template
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout-phase
        spec:
          targetState: deployed

  - name: phase-trafficrollout-ready-template
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout-phase

{{ end }}
