apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: UpgradePhase
metadata:
  name: upgrade-phase
spec:
  openstackServiceName: keystone
  targetOpenstackServiceVersion: moc.version.to.upgrade.to
  targetState: deployed
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/keystone
    subpath: .

  storageType: offsite
  backupPolicy:
    timeoutInSecond: 3
  # ceph:
  #   cephSecret: thesecret
  #   path: example
  clientTLSSecret: client.crt
  offsite:
    endpoint: sftp://foo.bar
    forcePathStyle: true
    offsiteSecret: thesecret
    path: xxx
  openstackEndpoints:
  - https://tar.com
