apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: openstackrestore-wf
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["workflow 3: openstackrestore"]
