apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: UpgradePhase
metadata:
  name: upgrade
spec:
  openstackVersion: moc.version.to.upgrade.to
  openstackRevision: 3
  storageType: offsite
  backupPolicy:
    timeoutInSecond: 3
  # ceph:
  #   cephSecret: thesecret
  #   path: example
  clientTLSSecret: client.crt
  offsite:
    endpoint: sftp://foo.bar
    forcePathStyle: true
    offsiteSecret: thesecret
    path: xxx
  openstackEndpoints:
  - https://local.com
  target_state: deployed
