---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: Oslc
metadata:
  name: testservice-upgrade
spec:
  serviceName: testservice
  source:
    type: generate
    location: /opt/openstacklcm-operator/helm-charts/testservice
  flowKind: upgrade
  targetState: deployed
