apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf-testchart-backup
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["workflow 1: testchart-backup"]
