---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: keystone
spec:
  chart_name: keystone
  test:
    enabled: true
  release: keystone
  namespace: openstack
  wait:
    timeout: 100
    labels:
      release_group: armada-keystone
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - name: keystone-bootstrap
          type: job
          labels:
            application: keystone
            component: bootstrap
  values:
    replicas: 3
#  values:
#    bootstrap:
#      script: |
#        openstack domain create 'ucp'
#        openstack project create --domain 'ucp' 'service'
#        openstack user create --domain ucp --project service --project-domain 'ucp' --password armada armada
#        openstack role add --project-domain ucp --user-domain ucp --user armada --project service admin
  source:
    type: git
    location: https://git.openstack.org/openstack/openstack-helm
    subpath: keystone
    reference: master
  dependencies:
    - helm-toolkit
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChartGroup
metadata:
  name: openstack-keystone
spec:
  description: "Deploying OpenStack Keystone"
  sequenced: True
  chart_group:
    - keystone
