{{- if eq .Values.oslc.flow_kind "rollback" }}
{{- $envAll := . }}

---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: RollbackPhase
metadata:
  name: {{ .Values.serviceName }}-rollback
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.rollback.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}

  backupStorageType: offsite
  # ceph:
  #   cephSecret: thesecret
  #   path: example
  offsite:
    endpoint: sftp://foo.bar
    forcePathStyle: true
    offsiteSecret: thesecret
    path: xxx
  openstackEndpoints:
  - https://tar.com
---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TrafficDrainPhase
metadata:
  name: {{ .Values.serviceName }}-trafficdrain
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.trafficdrain.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TrafficRolloutPhase
metadata:
  name: {{ .Values.serviceName }}-trafficrollout
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.trafficrollout.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ $envAll.Release.Name }}
spec:
  entrypoint: {{ $envAll.Release.Name }}
  serviceAccountName: openstacklcm-argo-sa
  templates:
  - name: {{ $envAll.Release.Name }}
    steps:
    - - name: {{ .Values.serviceName }}-operational-ready
        template: phase-operational-ready-template

    - - name: {{ .Values.serviceName }}-enable-trafficdrain
        template: enable-trafficdrain-template
    - - name: {{ .Values.serviceName }}-trafficdrain-ready
        template: phase-trafficdrain-ready-template

    - - name: {{ .Values.serviceName }}-enable-rollback
        template: enable-rollback-template
    - - name: {{ .Values.serviceName }}-rollback-ready
        template: phase-rollback-ready-template

    - - name: {{ .Values.serviceName }}-enable-trafficrollout
        template: enable-trafficrollout-template
    - - name: {{ .Values.serviceName }}-trafficrollout-ready
        template: phase-trafficrollout-ready-template

  - name: phase-operational-ready-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.wait_phase_operational }}
    retryStrategy:
      limit: {{ .Values.phases.retries.wait_phase_operational }}
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: OperationalPhase
        metadata:
          name: {{ .Values.serviceName }}-operational

  - name: enable-trafficdrain-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.enable_phase_trafficdrain }}
    retryStrategy:
      limit: {{ .Values.phases.retries.enabled_phase_trafficdrain }}
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficDrainPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficdrain
        spec:
          targetState: deployed

  - name: phase-trafficdrain-ready-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.wait_phase_trafficdrain }}
    retryStrategy:
      limit: {{ .Values.phases.retries.wait_phase_trafficdrain }}
    resource:
      action: get
      successCondition: status.actualState == deployed
      failureCondition: status.actualState == failed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficDrainPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficdrain

  - name: enable-rollback-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.enable_phase_rollback }}
    retryStrategy:
      limit: {{ .Values.phases.retries.enabled_phase_rollback }}
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: RollbackPhase
        metadata:
          name: {{ .Values.serviceName }}-rollback
        spec:
          targetState: deployed

  - name: phase-rollback-ready-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.wait_phase_rollback }}
    retryStrategy:
      limit: {{ .Values.phases.retries.wait_phase_rollback }}
    resource:
      action: get
      successCondition: status.actualState == deployed
      failureCondition: status.actualState == failed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: RollbackPhase
        metadata:
          name: {{ .Values.serviceName }}-rollback

  - name: enable-trafficrollout-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.enable_phase_trafficrollout }}
    retryStrategy:
      limit: {{ .Values.phases.retries.enabled_phase_trafficrollout }}
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout
        spec:
          targetState: deployed

  - name: phase-trafficrollout-ready-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.wait_phase_trafficrollout }}
    retryStrategy:
      limit: {{ .Values.phases.retries.wait_phase_trafficrollout }}
    resource:
      action: get
      successCondition: status.actualState == deployed
      failureCondition: status.actualState == failed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout

{{ end }}
