{{- if eq .Values.oslc.flow_kind "upgrade" }}
{{- $envAll := . }}

---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TestPhase
metadata:
  name: {{ .Values.serviceName }}-test
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.test.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TrafficDrainPhase
metadata:
  name: {{ .Values.serviceName }}-trafficdrain
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.trafficdrain.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: TrafficRolloutPhase
metadata:
  name: {{ .Values.serviceName }}-trafficrollout
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.trafficrollout.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}
---
apiVersion: openstacklcm.airshipit.org/v1alpha1
kind: UpgradePhase
metadata:
  name: {{ .Values.serviceName }}-upgrade
spec:
  openstackServiceName: {{ .Values.serviceName }}
  targetOpenstackServiceVersion: moc.version.to.upgrade.to
  targetState: uninitialized
  source:
    type: tar
    location: /opt/openstacklcm-operator/helm-charts/{{ .Values.serviceName }}

  storageType: offsite
  backupPolicy:
    timeoutInSecond: 3
  # ceph:
  #   cephSecret: thesecret
  #   path: example
  clientTLSSecret: client.crt
  offsite:
    endpoint: sftp://foo.bar
    forcePathStyle: true
    offsiteSecret: thesecret
    path: xxx
  openstackEndpoints:
  - https://tar.com
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ $envAll.Release.Name }}
spec:
  entrypoint: {{ $envAll.Release.Name }}
  serviceAccountName: openstacklcm-argo-sa
  templates:
  - name: {{ $envAll.Release.Name }}
    steps:
    - - name: {{ .Values.serviceName }}-operational-ready
        template: phase-operational-ready-template

    - - name: {{ .Values.serviceName }}-enable-trafficdrain
        template: enable-trafficdrain-template
    - - name: {{ .Values.serviceName }}-trafficdrain-ready
        template: phase-trafficdrain-ready-template

    - - name: {{ .Values.serviceName }}-enable-upgrade
        template: enable-upgrade-template
    - - name: {{ .Values.serviceName }}-upgrade-ready
        template: phase-upgrade-ready-template

    - - name: {{ .Values.serviceName }}-enable-test
        template: enable-test-template
    - - name: {{ .Values.serviceName }}-test-ready
        template: phase-test-ready-template
        continueOn:
           failed: {{ .Values.continue_on_test_failed }}

    - - name: {{ .Values.serviceName }}-enable-rollback
        template: enable-rollback-template
        when: "{{steps."{{ .Values.serviceName }}".test-ready.outputs.result}} == failed"
    - - name: {{ .Values.serviceName }}-rollback-ready
        template: phase-rollback-ready-template
        when: "{{steps."{{ .Values.serviceName }}".test-ready.outputs.result}} == failed"

    - - name: {{ .Values.serviceName }}-enable-trafficrollout
        template: enable-trafficrollout-template
    - - name: {{ .Values.serviceName }}-trafficrollout-ready
        template: phase-trafficrollout-ready-template

  - name: phase-operational-ready-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.wait_phase_operational }}
    retryStrategy:
      limit: {{ .Values.phases.retries.wait_phase_operational }}
    resource:
      action: get
      successCondition: status.actualState == deployed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: OperationalPhase
        metadata:
          name: {{ .Values.serviceName }}-operational

  - name: enable-trafficdrain-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.enable_phase_trafficdrain }}
    retryStrategy:
      limit: {{ .Values.phases.retries.enabled_phase_trafficdrain }}
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficDrainPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficdrain
        spec:
          targetState: deployed

  - name: phase-trafficdrain-ready-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.wait_phase_trafficdrain }}
    retryStrategy:
      limit: {{ .Values.phases.retries.wait_phase_trafficdrain }}
    resource:
      action: get
      successCondition: status.actualState == deployed
      failureCondition: status.actualState == failed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficDrainPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficdrain

  - name: enable-upgrade-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.enable_phase_upgrade }}
    retryStrategy:
      limit: {{ .Values.phases.retries.enabled_phase_upgrade }}
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: UpgradePhase
        metadata:
          name: {{ .Values.serviceName }}-upgrade
        spec:
          targetState: deployed

  - name: phase-upgrade-ready-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.wait_phase_upgrade }}
    retryStrategy:
      limit: {{ .Values.phases.retries.wait_phase_upgrade }}
    resource:
      action: get
      successCondition: status.actualState == deployed
      failureCondition: status.actualState == failed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: UpgradePhase
        metadata:
          name: {{ .Values.serviceName }}-upgrade

  - name: phase-test-ready-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.wait_phase_test }}
    retryStrategy:
      limit: {{ .Values.phases.retries.wait_phase_test }}
    resource:
      action: get
      successCondition: status.actualState == deployed
      failureCondition: status.actualState == failed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TestPhase
        metadata:
          name: {{ .Values.serviceName }}-test

  - name: enable-test-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.enable_phase_test }}
    retryStrategy:
      limit: {{ .Values.phases.retries.enabled_phase_test }}
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TestPhase
        metadata:
          name: {{ .Values.serviceName }}-test
        spec:
          targetState: deployed

  - name: phase-rollback-ready-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.wait_phase_rollback }}
    retryStrategy:
      limit: {{ .Values.phases.retries.wait_phase_rollback }}
    resource:
      action: get
      successCondition: status.actualState == deployed
      failureCondition: status.actualState == failed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: RollbackPhase
        metadata:
          name: {{ .Values.serviceName }}-rollback

  - name: enable-trafficrollout-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.enable_phase_trafficrollout }}
    retryStrategy:
      limit: {{ .Values.phases.retries.enabled_phase_trafficrollout }}
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout
        spec:
          targetState: deployed

  - name: enable-trafficrollout-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.enable_phase_trafficrollout }}
    retryStrategy:
      limit: {{ .Values.phases.retries.enabled_phase_trafficrollout }}
    resource:
      action: patch
      mergeStrategy: merge
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout
        spec:
          targetState: deployed

  - name: phase-trafficrollout-ready-template
    activeDeadlineSeconds: {{ .Values.phases.timeout.wait_phase_trafficrollout }}
    retryStrategy:
      limit: {{ .Values.phases.retries.wait_phase_trafficrollout }}
    resource:
      action: get
      successCondition: status.actualState == deployed
      failureCondition: status.actualState == failed
      manifest: |
        apiVersion: openstacklcm.airshipit.org/v1alpha1
        kind: TrafficRolloutPhase
        metadata:
          name: {{ .Values.serviceName }}-trafficrollout
{{ end }}
