---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: rabbitmq
spec:
  chart_name: rabbitmq
  test:
    enabled: true
  release: rabbitmq
  namespace: openstack
  wait:
    timeout: 100
    labels:
      release_group: armada-rabbitmq
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: local
    location: /opt/armada/helm-charts/rabbitmq
    subpath: .
    reference: master
  dependencies:
    - helm-toolkit
