// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChart) DeepCopyInto(out *ArmadaChart) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChart.
func (in *ArmadaChart) DeepCopy() *ArmadaChart {
	if in == nil {
		return nil
	}
	out := new(ArmadaChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArmadaChart) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartGroup) DeepCopyInto(out *ArmadaChartGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartGroup.
func (in *ArmadaChartGroup) DeepCopy() *ArmadaChartGroup {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArmadaChartGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartGroupList) DeepCopyInto(out *ArmadaChartGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArmadaChartGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartGroupList.
func (in *ArmadaChartGroupList) DeepCopy() *ArmadaChartGroupList {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArmadaChartGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartGroupSpec) DeepCopyInto(out *ArmadaChartGroupSpec) {
	*out = *in
	if in.Charts != nil {
		in, out := &in.Charts, &out.Charts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartGroupSpec.
func (in *ArmadaChartGroupSpec) DeepCopy() *ArmadaChartGroupSpec {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartGroupStatus) DeepCopyInto(out *ArmadaChartGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]HelmResourceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartGroupStatus.
func (in *ArmadaChartGroupStatus) DeepCopy() *ArmadaChartGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartList) DeepCopyInto(out *ArmadaChartList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArmadaChart, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartList.
func (in *ArmadaChartList) DeepCopy() *ArmadaChartList {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArmadaChartList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartSource) DeepCopyInto(out *ArmadaChartSource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartSource.
func (in *ArmadaChartSource) DeepCopy() *ArmadaChartSource {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartSpec) DeepCopyInto(out *ArmadaChartSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(ArmadaChartSource)
		**out = **in
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(ArmadaChartValues)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(ArmadaDelete)
		**out = **in
	}
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(ArmadaUpgrade)
		(*in).DeepCopyInto(*out)
	}
	if in.Protected != nil {
		in, out := &in.Protected, &out.Protected
		*out = new(ArmadaProtectedRelease)
		**out = **in
	}
	if in.Test != nil {
		in, out := &in.Test, &out.Test
		*out = new(ArmadaTest)
		**out = **in
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(ArmadaWait)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartSpec.
func (in *ArmadaChartSpec) DeepCopy() *ArmadaChartSpec {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartStatus) DeepCopyInto(out *ArmadaChartStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]HelmResourceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartStatus.
func (in *ArmadaChartStatus) DeepCopy() *ArmadaChartStatus {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaChartValues) DeepCopyInto(out *ArmadaChartValues) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaChartValues.
func (in *ArmadaChartValues) DeepCopy() *ArmadaChartValues {
	if in == nil {
		return nil
	}
	out := new(ArmadaChartValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaDelete) DeepCopyInto(out *ArmadaDelete) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaDelete.
func (in *ArmadaDelete) DeepCopy() *ArmadaDelete {
	if in == nil {
		return nil
	}
	out := new(ArmadaDelete)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaHookActionItems) DeepCopyInto(out *ArmadaHookActionItems) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = new(ArmadaLabels)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaHookActionItems.
func (in *ArmadaHookActionItems) DeepCopy() *ArmadaHookActionItems {
	if in == nil {
		return nil
	}
	out := new(ArmadaHookActionItems)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaLabels) DeepCopyInto(out *ArmadaLabels) {
	*out = *in
	if in.AdditionalProperties != nil {
		in, out := &in.AdditionalProperties, &out.AdditionalProperties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaLabels.
func (in *ArmadaLabels) DeepCopy() *ArmadaLabels {
	if in == nil {
		return nil
	}
	out := new(ArmadaLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaManifest) DeepCopyInto(out *ArmadaManifest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaManifest.
func (in *ArmadaManifest) DeepCopy() *ArmadaManifest {
	if in == nil {
		return nil
	}
	out := new(ArmadaManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArmadaManifest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaManifestList) DeepCopyInto(out *ArmadaManifestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArmadaManifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaManifestList.
func (in *ArmadaManifestList) DeepCopy() *ArmadaManifestList {
	if in == nil {
		return nil
	}
	out := new(ArmadaManifestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArmadaManifestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaManifestSpec) DeepCopyInto(out *ArmadaManifestSpec) {
	*out = *in
	if in.ChartGroups != nil {
		in, out := &in.ChartGroups, &out.ChartGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaManifestSpec.
func (in *ArmadaManifestSpec) DeepCopy() *ArmadaManifestSpec {
	if in == nil {
		return nil
	}
	out := new(ArmadaManifestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaManifestStatus) DeepCopyInto(out *ArmadaManifestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]HelmResourceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaManifestStatus.
func (in *ArmadaManifestStatus) DeepCopy() *ArmadaManifestStatus {
	if in == nil {
		return nil
	}
	out := new(ArmadaManifestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaProtectedRelease) DeepCopyInto(out *ArmadaProtectedRelease) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaProtectedRelease.
func (in *ArmadaProtectedRelease) DeepCopy() *ArmadaProtectedRelease {
	if in == nil {
		return nil
	}
	out := new(ArmadaProtectedRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaTest) DeepCopyInto(out *ArmadaTest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaTest.
func (in *ArmadaTest) DeepCopy() *ArmadaTest {
	if in == nil {
		return nil
	}
	out := new(ArmadaTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaUpgrade) DeepCopyInto(out *ArmadaUpgrade) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(ArmadaUpgradeOptions)
		**out = **in
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = new(ArmadaUpgradePost)
		(*in).DeepCopyInto(*out)
	}
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		*out = new(ArmadaUpgradePre)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaUpgrade.
func (in *ArmadaUpgrade) DeepCopy() *ArmadaUpgrade {
	if in == nil {
		return nil
	}
	out := new(ArmadaUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaUpgradeOptions) DeepCopyInto(out *ArmadaUpgradeOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaUpgradeOptions.
func (in *ArmadaUpgradeOptions) DeepCopy() *ArmadaUpgradeOptions {
	if in == nil {
		return nil
	}
	out := new(ArmadaUpgradeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaUpgradePost) DeepCopyInto(out *ArmadaUpgradePost) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = make([]*ArmadaHookActionItems, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ArmadaHookActionItems)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaUpgradePost.
func (in *ArmadaUpgradePost) DeepCopy() *ArmadaUpgradePost {
	if in == nil {
		return nil
	}
	out := new(ArmadaUpgradePost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaUpgradePre) DeepCopyInto(out *ArmadaUpgradePre) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = make([]*ArmadaHookActionItems, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ArmadaHookActionItems)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = make([]*ArmadaHookActionItems, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ArmadaHookActionItems)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = make([]*ArmadaHookActionItems, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ArmadaHookActionItems)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaUpgradePre.
func (in *ArmadaUpgradePre) DeepCopy() *ArmadaUpgradePre {
	if in == nil {
		return nil
	}
	out := new(ArmadaUpgradePre)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaWait) DeepCopyInto(out *ArmadaWait) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = new(ArmadaLabels)
		(*in).DeepCopyInto(*out)
	}
	if in.Native != nil {
		in, out := &in.Native, &out.Native
		*out = new(ArmadaWaitNative)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]*ArmadaWaitResourcesItems, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ArmadaWaitResourcesItems)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaWait.
func (in *ArmadaWait) DeepCopy() *ArmadaWait {
	if in == nil {
		return nil
	}
	out := new(ArmadaWait)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaWaitNative) DeepCopyInto(out *ArmadaWaitNative) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaWaitNative.
func (in *ArmadaWaitNative) DeepCopy() *ArmadaWaitNative {
	if in == nil {
		return nil
	}
	out := new(ArmadaWaitNative)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArmadaWaitResourcesItems) DeepCopyInto(out *ArmadaWaitResourcesItems) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = new(ArmadaLabels)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArmadaWaitResourcesItems.
func (in *ArmadaWaitResourcesItems) DeepCopy() *ArmadaWaitResourcesItems {
	if in == nil {
		return nil
	}
	out := new(ArmadaWaitResourcesItems)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmChart) DeepCopyInto(out *HelmChart) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(HelmMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Lock != nil {
		in, out := &in.Lock, &out.Lock
		*out = new(HelmLock)
		(*in).DeepCopyInto(*out)
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]*HelmFile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(HelmFile)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.RawValues != nil {
		in, out := &in.RawValues, &out.RawValues
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	in.Values.DeepCopyInto(&out.Values)
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]*HelmFile, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(HelmFile)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.parent != nil {
		in, out := &in.parent, &out.parent
		*out = new(HelmChart)
		(*in).DeepCopyInto(*out)
	}
	if in.dependencies != nil {
		in, out := &in.dependencies, &out.dependencies
		*out = make([]*HelmChart, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(HelmChart)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmChart.
func (in *HelmChart) DeepCopy() *HelmChart {
	if in == nil {
		return nil
	}
	out := new(HelmChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmDependency) DeepCopyInto(out *HelmDependency) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ImportValues.DeepCopyInto(&out.ImportValues)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmDependency.
func (in *HelmDependency) DeepCopy() *HelmDependency {
	if in == nil {
		return nil
	}
	out := new(HelmDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmFile) DeepCopyInto(out *HelmFile) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmFile.
func (in *HelmFile) DeepCopy() *HelmFile {
	if in == nil {
		return nil
	}
	out := new(HelmFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmHook) DeepCopyInto(out *HelmHook) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]HelmHookEvent, len(*in))
		copy(*out, *in)
	}
	in.LastRun.DeepCopyInto(&out.LastRun)
	if in.DeletePolicies != nil {
		in, out := &in.DeletePolicies, &out.DeletePolicies
		*out = make([]HelmHookDeletePolicy, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmHook.
func (in *HelmHook) DeepCopy() *HelmHook {
	if in == nil {
		return nil
	}
	out := new(HelmHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmInfo) DeepCopyInto(out *HelmInfo) {
	*out = *in
	in.FirstDeployed.DeepCopyInto(&out.FirstDeployed)
	in.LastDeployed.DeepCopyInto(&out.LastDeployed)
	in.Deleted.DeepCopyInto(&out.Deleted)
	if in.LastTestSuiteRun != nil {
		in, out := &in.LastTestSuiteRun, &out.LastTestSuiteRun
		*out = new(HelmTestSuite)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmInfo.
func (in *HelmInfo) DeepCopy() *HelmInfo {
	if in == nil {
		return nil
	}
	out := new(HelmInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmLock) DeepCopyInto(out *HelmLock) {
	*out = *in
	in.Generated.DeepCopyInto(&out.Generated)
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]*HelmDependency, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(HelmDependency)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmLock.
func (in *HelmLock) DeepCopy() *HelmLock {
	if in == nil {
		return nil
	}
	out := new(HelmLock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmMaintainer) DeepCopyInto(out *HelmMaintainer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmMaintainer.
func (in *HelmMaintainer) DeepCopy() *HelmMaintainer {
	if in == nil {
		return nil
	}
	out := new(HelmMaintainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmMetadata) DeepCopyInto(out *HelmMetadata) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Keywords != nil {
		in, out := &in.Keywords, &out.Keywords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Maintainers != nil {
		in, out := &in.Maintainers, &out.Maintainers
		*out = make([]*HelmMaintainer, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(HelmMaintainer)
				**out = **in
			}
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]*HelmDependency, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(HelmDependency)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmMetadata.
func (in *HelmMetadata) DeepCopy() *HelmMetadata {
	if in == nil {
		return nil
	}
	out := new(HelmMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmRelease) DeepCopyInto(out *HelmRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmRelease.
func (in *HelmRelease) DeepCopy() *HelmRelease {
	if in == nil {
		return nil
	}
	out := new(HelmRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseDesc) DeepCopyInto(out *HelmReleaseDesc) {
	*out = *in
	if in.Info != nil {
		in, out := &in.Info, &out.Info
		*out = new(HelmInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Chart != nil {
		in, out := &in.Chart, &out.Chart
		*out = new(HelmChart)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = (*in).DeepCopy()
	}
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = make([]*HelmHook, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(HelmHook)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseDesc.
func (in *HelmReleaseDesc) DeepCopy() *HelmReleaseDesc {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseDesc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseList) DeepCopyInto(out *HelmReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelmRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseList.
func (in *HelmReleaseList) DeepCopy() *HelmReleaseList {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseSpec) DeepCopyInto(out *HelmReleaseSpec) {
	*out = *in
	if in.ReleaseDesc != nil {
		in, out := &in.ReleaseDesc, &out.ReleaseDesc
		*out = new(HelmReleaseDesc)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseSpec.
func (in *HelmReleaseSpec) DeepCopy() *HelmReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseStatus) DeepCopyInto(out *HelmReleaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]HelmResourceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseStatus.
func (in *HelmReleaseStatus) DeepCopy() *HelmReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmResourceCondition) DeepCopyInto(out *HelmResourceCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmResourceCondition.
func (in *HelmResourceCondition) DeepCopy() *HelmResourceCondition {
	if in == nil {
		return nil
	}
	out := new(HelmResourceCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmResourceConditionListHelper) DeepCopyInto(out *HelmResourceConditionListHelper) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelmResourceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmResourceConditionListHelper.
func (in *HelmResourceConditionListHelper) DeepCopy() *HelmResourceConditionListHelper {
	if in == nil {
		return nil
	}
	out := new(HelmResourceConditionListHelper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmTestRun) DeepCopyInto(out *HelmTestRun) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmTestRun.
func (in *HelmTestRun) DeepCopy() *HelmTestRun {
	if in == nil {
		return nil
	}
	out := new(HelmTestRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmTestSuite) DeepCopyInto(out *HelmTestSuite) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]*HelmTestRun, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(HelmTestRun)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmTestSuite.
func (in *HelmTestSuite) DeepCopy() *HelmTestSuite {
	if in == nil {
		return nil
	}
	out := new(HelmTestSuite)
	in.DeepCopyInto(out)
	return out
}
