#!/bin/bash
GOODPATH=`pwd`
for i in armada-operator mariadb-operator memcached-operator rabbitmq-operator openstacklcm-operator keystone-operator
do
cd $i
echo "=================" " Cleaning: " $i "==================="
make clean
cd $GOODPATH
done
#
for i in armada-operator openstacklcm-operator
do
cd $i
echo "=================" " Computing dependencies: " $i "==================="
dep ensure
cd $GOODPATH
done
#
for i in armada-operator mariadb-operator memcached-operator rabbitmq-operator openstacklcm-operator keystone-operator
do
cd $i
echo "=================" " Building: " $i "==================="
make docker-build
cd $GOODPATH
done
