apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystone-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keystone-operator
  template:
    metadata:
      labels:
        name: keystone-operator
    spec:
      serviceAccountName: armada-operator
      containers:
        - name: keystone-operator
          # Replace this with the built image name
          image: kubekit99/keystone-operator:poc
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keystone-operator"
