apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keystones.openstackhelm.openstack.org
spec:
  group: openstackhelm.openstack.org
  names:
    kind: Keystone
    listKind: KeystoneList
    plural: keystones
    singular: keystone
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
