apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mariadbs.openstackhelm.openstack.org
spec:
  group: openstackhelm.openstack.org
  names:
    kind: Mariadb
    listKind: MariadbList
    plural: mariadbs
    singular: mariadb
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
