apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: lifecyleevents.helm3crd.airshipit.org
spec:
  group: helm3crd.airshipit.org
  names:
    kind: LifecycleEvent
    plural: lifecyleevents
    shortNames:
    - le
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            config:
              properties:
                podName:
                  type: string
              type: object
            timeout:
              format: int64
              type: integer
          type: object
        status:
          properties:
            error:
              description: Will be set to true if there was an error with `message`
                containing more info
              type: boolean
            message:
              type: string
            phase:
              description: Will be marked as "Running" if in progress, "Pending" if
                it hasn't been handled yet, and "Error" if it is in an error state
              type: string
          required:
          - error
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
